### ISSUE TITLE
[Bug]  Video stops playing after 1 min

### ISSUE THREAD

**Issue by Rishang** [cuynu/ytvanced#120] opened 2023-03-04 11:41 UTC
Video stops playing after around 1 min for any youtube video, also i have tried for all types of apk for this specific version release

Environment
===========
Platform:Android
OS Version: 12
YouTube Vanced Version: 18.01.3
Vanced MicroG: 
Device: mi note7 pro (sakura)

Description
===========
When i play any random video on this app, it plays it normally as expected but after 50 seconds it stops playing and gose in loading.. maybe its a buffering issue so i tried following things.

- Enable fix buffet flag
- Disable youtube dislike and youtube sponsor ads flag
- relaunch app after forcestop and clear cache

Even after that i am unable to solve it and it's not an internet issue which i am shure about.

Steps to reproduce
==================
1. Open application
2. Play any video which i above 1 min
3. seet it for around 60 sec, and then you should face loading black screen and video will be stuck over there

Expected result
===============
Video should be able to play smoothly

**Comment by Usmanali429** [comment] 2023-03-05 08:39
Yeh i try extended or normal version both have bug video stop after 1 min plz fix

**Comment by Rishang** [comment] 2023-03-05 09:02
@cuynu I only have single account, can there be any way to fix it ?

**Comment by erikmon** [comment] 2023-03-05 14:23
This problem can be avoided if you log out

**Comment by Fuksi-docktor** [comment] 2023-03-05 18:16
Ich glaube aufrichtig, dass es dieses Problem lösen wird.

**Comment by Fuksi-docktor** [comment] 2023-03-05 18:17
I sincerely believe that it will solve this problem.

**Comment by Fuksi-docktor** [comment] 2023-03-05 18:47
> Oturumu kapatırsanız bu sorun önlenebilir

that's true but most people don't want to watch videos in incognito mode

**Comment by cuynu** [comment] 2023-03-06 00:41
> @cuynu I only have single account, can there be any way to fix it ?

No. Google is blocking you

**Comment by hiroshil** [comment] 2023-03-07 12:21
bản revanced ko bị lỗi này á 

> > @cuynu I only have single account, can there be any way to fix it ?
> 
> No. Google is blocking you

t cũng bị lỗi này. nhưng khi dùng revanced thì ko bị

**Comment by MaurilioBF** [comment] 2023-03-07 13:24
I'm using version 18.01.38 Black, and it's working perfectly, without any problems. Thank you very much Coder!

**Comment by Rishang** [comment] 2023-03-08 05:21
I tried vanced today, it was playing well but don't know how long it will be the same

**Comment by cuynu** [comment] 2023-03-08 07:48
fk

Vào 19:21, Th 3, 7 thg 3, 2023 Hiroshi ***@***.***> đã viết:

**Comment by cuynu** [comment] 2023-03-08 07:49
do not speak vietnamese

**Comment by hiroshil** [comment] 2023-03-08 10:12
Không thể tải lên tệp

**Comment by testermania** [comment] 2023-03-09 07:07
same for 17.34.36

**Comment by longtengyiyu** [comment] 2023-03-10 14:36
logout -- login

**Comment by cuynu** [comment] 2023-03-10 14:41
please create new brand channel

**Comment by SuperfieldCU** [comment] 2023-03-12 20:36
Can confirm that switch from Dark to Black resolves the problem. Definitely do so if you are experiencing this problem on Dark.

**Comment by NaorAnhaisy** [comment] 2023-03-22 11:36
Hi, is there any fix for that?

**Comment by cuynu** [comment] 2023-03-24 22:25
> Hi, is there any fix for that?

use 18.02.33

**Comment by NaorAnhaisy** [comment] 2023-03-26 06:41
> > Hi, is there any fix for that?
> 
> use 18.02.33

I don't see any realse of that version. Did you realse it?

**Comment by geojimas** [comment] 2023-03-26 12:25
> > > Hi, is there any fix for that?
> > 
> > 
> > use 18.02.33
> 
> I don't see any realse of that version. Did you realse it?

Here ::  https://github.com/cuynu/ytvanced/releases/tag/18.02.33

**Comment by IvarWithoutBones** [comment] 2023-04-11 12:07
> > Hi, is there any fix for that?
> 
> use 18.02.33

Even on the that release, I am unfortunately still hit with this issue. Do you mean that using revision 18.02.33 will prevent your account from being flagged in the first place, but will not fix this problem if it already is?

**Comment by cuynu** [comment] 2023-04-11 12:11
> > > Hi, is there any fix for that?
> > 
> > 
> > use 18.02.33
> 
> Even on the that release, I am unfortunately still hit with this issue. Do you mean that using revision 18.02.33 will prevent your account from being flagged in the first place, but will not fix this problem if it already is?

You must use `black` theme variant, it's should fix playback issue

**Comment by geojimas** [comment] 2023-04-11 12:16
> > > Hi, is there any fix for that?
> > 
> > 
> > use 18.02.33
> 
> Even on the that release, I am unfortunately still hit with this issue. Do you mean that using revision 18.02.33 will prevent your account from being flagged in the first place, but will not fix this problem if it already is?

i had the same problem with flagged account and with this release the problem is solved, use this apk : [YouTube.Vanced.v18.02.33_Black_Universal.apk](https://github.com/cuynu/ytvanced/releases/download/18.02.33/YouTube.Vanced.v18.02.33_Black_Universal.apk)

**Comment by nyaasar** [comment] 2023-04-12 18:57
So there are really no other solution than changing account or upgrading OS to Android 8, huh?

Guess it's time to use the official app then. 😥

**Comment by cuynu** [comment] 2023-04-12 18:59
> So there are really no other solution than changing account or upgrading OS to Android 8, huh?
> 
> Guess it's time to use the official app then. 😥

u use android 6 & 7?

**Comment by alcatraz-zz** [comment] 2023-04-13 02:52
I also have this issue. I noticed that on my phone running Revanced Extended I don't have this problem with the same microg version.

Yes, I have a couple of beautiful samsung oled tablets running android 6. I tried your version (thanks btw) and it works except for this 1min thing.

Is there any way of making a 17.34.36 Revanced Extended?

**Comment by alcatraz-zz** [comment] 2023-04-13 10:40
Original vanced 17.03.38 didn't have this 1min stop problem. (Neither does Revanced Extended) I think you're on to something with this apk here.

Do you think it's possible to spoof the version of the original vanced 17.03.38 apk?

I think I saw the patch available in Revanced Manager for original Vanced, but I couldn't get it to work hmm. Anyone tried it?

**Comment by cuynu** [comment] 2023-04-13 10:43
> Original vanced 17.03.38 didn't have this 1min stop problem. (Neither does Revanced Extended) I think you're on to something with this apk here.
> 
> Do you think it's possible to spoof the version of the original vanced 17.03.38 apk?
> 
> I think I saw the patch available in Revanced Manager for original Vanced, but I couldn't get it to work hmm. Anyone tried it?

17.03.38 are impossible to spoof newer version, it's will crash itself or buggy

**Comment by alcatraz-zz** [comment] 2023-04-13 11:23
Any idea why Revanced Extended v18 doesn't have the 1 min problem? 

Maybe they're patching something that wasn't available for v17 hmm.

**Comment by cuynu** [comment] 2023-04-13 11:27
> Any idea why Revanced Extended v18 doesn't have the 1 min problem?
> 
> Maybe they're patching something that wasn't available for v17 hmm.

this not a place for talking about revanced patch since i stopped using it

**Comment by alcatraz-zz** [comment] 2023-04-13 13:54
Ok sorry. If there's anything I can do to help/test a different ytvanced for android 6/7, please don't hesistate to ask.

I know there's demand, because people are asking for it everywhere.

You got closest to providing a working version. It's 99%

I know there are alternative players but none that support sign-in.

**Comment by TrainedPro** [comment] 2023-04-13 16:22
Android: 7
Device: Samsung Tab S2
Vanced Version : 17.34.36 (Spoofed For 18.xx)

Have the same issue, tried turning spoofing off and also turning on the buffer setting, even alternated between the both but didn't seem to help. Removed account, cleared data, changed nothing. Although on my newer phone (Android 13), the proper ReVanced seems to work perfectly fine, with the exact same account.

Interesting enough, using a VPN made it go from like 1 minute to 2 minutes. **I did manage to get it working**. IDK how exactly i did it but i turned on incognito (In which it works perfectly fine). After it being off for a while or maybe i forced stopped it, it was logged into my account but also in incognito.

Unfortunately i thought it was a glitch so i basically "fixed" it by turning incognito on and off and now it's back to not working.

More than happy to help, so let me know if you need any more info!

**Comment by cuynu** [comment] 2023-04-13 16:41
> Android: 7 Device: Samsung Tab S2 Vanced Version : 17.34.36 (Spoofed For 18.xx)
> 
> Have the same issue, tried turning spoofing off and also turning on the buffer setting, even alternated between the both but didn't seem to help. Removed account, cleared data, changed nothing. Although on my newer phone (Android 13), the proper ReVanced seems to work perfectly fine, with the exact same account.
> 
> Interesting enough, using a VPN made it go from like 1 minute to 2 minutes. **I did manage to get it working**. IDK how exactly i did it but i turned on incognito (In which it works perfectly fine). After it being off for a while or maybe i forced stopped it, it was logged into my account but also in incognito.
> 
> Unfortunately i thought it was a glitch so i basically "fixed" it by turning incognito on and off and now it's back to not working.
> 
> More than happy to help, so let me know if you need any more info!

17.34.36 is no longer updated anymore, the only solution is change other Google account/Channel or use in signed out mode for Android 7 users

**Comment by nyaasar** [comment] 2023-04-13 18:27
> > So there are really no other solution than changing account or upgrading OS to Android 8, huh?
> > Guess it's time to use the official app then. 😥
> 
> u use android 6 & 7?

Unfortunately, yes. 
I'm currently using a Redmi 4X with God-knows-whom-locked Mi account and locked bootloader, so there's no way for me to install custom ROM for this phone. I can't afford a new phone right now, and using the official app is also out of question.

My only get around of this problem is by using Firefox app + uBlock and Video background fix addons.

**Comment by alcatraz-zz** [comment] 2023-04-13 23:56
If anyone finds a way please write it in this conversation. Thanks!

I'm super happy with how original Vanced worked. It was great. Pity it can't be spoofed.

Do you think there's a version between 17.03.38 and 17.34.36 that can be spoofed? (I know you wrote many times the patches don't work for old versions. I'm just thinking out loud.)

**Comment by cuynu** [comment] 2023-04-14 00:13
> If anyone finds a way please write it in this conversation. Thanks!
> 
> I'm super happy with how original Vanced worked. It was great. Pity it can't be spoofed.
> 
> Do you think there's a version between 17.03.38 and 17.34.36 that can be spoofed? (I know you wrote many times the patches don't work for old versions. I'm just thinking out loud.)
> 
> Many TV sets are running android 6. I used to run youtube vanced on one and it worked fine with a bluetooth mouse. How many TV sets are out there? Great reason for a working andoid 6 vanced. 😁 And no it wasn't a Google TV or Chromecast so I couldn't install Youtube TV (which has ads by the way).

17.33.xx+ can spoof to newer version when i try to spoof, but 17.0x.xx< are crashing or crash when i tries spoof
If your TV is Android, try SmartTube

**Comment by lightningHoneypot** [comment] 2023-04-14 06:02
Where is the seeking preview on the beta? I don't see it 

Example: ![Screenshot_20230414-000116_YouTube Vanced.jpg](https://user-images.githubusercontent.com/88814097/231954494-000dc95f-bb73-4aa5-963d-f87448e186ea.jpg)

**Comment by FaboThePlayer** [comment] 2023-04-14 08:33
> > > > Hi, is there any fix for that?
> > > 
> > > 
> > > use 18.02.33
> > 
> > 
> > Even on the that release, I am unfortunately still hit with this issue. Do you mean that using revision 18.02.33 will prevent your account from being flagged in the first place, but will not fix this problem if it already is?
> 
> i had the same problem with flagged account and with this release the problem is solved, use this apk : [YouTube.Vanced.v18.02.33_Black_Universal.apk](https://github.com/cuynu/ytvanced/releases/download/18.02.33/YouTube.Vanced.v18.02.33_Black_Universal.apk)

Don't work for me in my general account.

**Comment by cuynu** [comment] 2023-04-14 08:36
> > > > > Hi, is there any fix for that?
> > > > 
> > > > 
> > > > use 18.02.33
> > > 
> > > 
> > > Even on the that release, I am unfortunately still hit with this issue. Do you mean that using revision 18.02.33 will prevent your account from being flagged in the first place, but will not fix this problem if it already is?
> > 
> > 
> > i had the same problem with flagged account and with this release the problem is solved, use this apk : [YouTube.Vanced.v18.02.33_Black_Universal.apk](https://github.com/cuynu/ytvanced/releases/download/18.02.33/YouTube.Vanced.v18.02.33_Black_Universal.apk)
> 
> Don't work for me in my general account.

try hotfix release, enable protobuf spoof in vanced settings -> video and give feedback

**Comment by FaboThePlayer** [comment] 2023-04-14 08:42
W

> > > > > > Hi, is there any fix for that?
> > > > > 
> > > > > 
> > > > > use 18.02.33
> > > > 
> > > > 
> > > > Even on the that release, I am unfortunately still hit with this issue. Do you mean that using revision 18.02.33 will prevent your account from being flagged in the first place, but will not fix this problem if it already is?
> > > 
> > > 
> > > i had the same problem with flagged account and with this release the problem is solved, use this apk : [YouTube.Vanced.v18.02.33_Black_Universal.apk](https://github.com/cuynu/ytvanced/releases/download/18.02.33/YouTube.Vanced.v18.02.33_Black_Universal.apk)
> > 
> > 
> > Don't work for me in my general account.
> 
> try hotfix release, enable protobuf spoof in vanced settings -> video and give feedback

Thanks! It seems to work!

**Comment by S0GDevs** [comment] 2023-04-14 17:34
> Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account

I believe issue is related to the fact that we login through MicroG instead of traditional login system. I'll try setting up a listener to review the requests/responses to try identify what could trigger Google buffer block

**Comment by cuynu** [comment] 2023-04-14 17:36
> > Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account
> 
> I believe issue is related to the fact that we login through MicroG instead of traditional login system. I'll try setting up a listener to review the requests/responses to try identify what could trigger Google buffer block

There's solution for buffer issue, update to 18.02.33 hotfix should fix buffer issue

**Comment by cuynu** [comment] 2023-04-14 17:45
> > > > Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account
> > > 
> > > 
> > > I believe issue is related to the fact that we login through MicroG instead of traditional login system. I'll try setting up a listener to review the requests/responses to try identify what could trigger Google buffer block
> > 
> > 
> > There's solution for buffer issue, update to 18.02.33 hotfix should fix buffer issue
> 
> I confirm the hotfix after enabling VP9 Codec in Vanced settings. Perhaps making it turned on by default in futur release could avoid further issues?

the right fix buffer option is `spoof protobuf`.

**Comment by S0GDevs** [comment] 2023-04-14 17:47
> > > > > Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account
> > > > 
> > > > 
> > > > I believe issue is related to the fact that we login through MicroG instead of traditional login system. I'll try setting up a listener to review the requests/responses to try identify what could trigger Google buffer block
> > > 
> > > 
> > > There's solution for buffer issue, update to 18.02.33 hotfix should fix buffer issue
> > 
> > 
> > I confirm the hotfix after enabling VP9 Codec in Vanced settings. Perhaps making it turned on by default in futur release could avoid further issues?
> 
> the right fix buffer option is `spoof protobuf`.

Weird, I still had the buffer lock with Protobuf but it unlocked when enabling VP9 Codec.
Perhaps videos uploaded with VP9 are locked still locked?

**Comment by cuynu** [comment] 2023-04-14 17:49
> > > > > > Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account
> > > > > 
> > > > > 
> > > > > I believe issue is related to the fact that we login through MicroG instead of traditional login system. I'll try setting up a listener to review the requests/responses to try identify what could trigger Google buffer block
> > > > 
> > > > 
> > > > There's solution for buffer issue, update to 18.02.33 hotfix should fix buffer issue
> > > 
> > > 
> > > I confirm the hotfix after enabling VP9 Codec in Vanced settings. Perhaps making it turned on by default in futur release could avoid further issues?
> > 
> > 
> > the right fix buffer option is `spoof protobuf`.
> 
> Weird, I still had the buffer lock with Protobuf but it unlocked when enabling VP9 Codec. Perhaps videos uploaded with VP9 are still locked?

i don't know but most ppl are able to fix buffer issue with protobuf spoof option

**Comment by S0GDevs** [comment] 2023-04-14 17:50
> > > > > > > Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account
> > > > > > 
> > > > > > 
> > > > > > I believe issue is related to the fact that we login through MicroG instead of traditional login system. I'll try setting up a listener to review the requests/responses to try identify what could trigger Google buffer block
> > > > > 
> > > > > 
> > > > > There's solution for buffer issue, update to 18.02.33 hotfix should fix buffer issue
> > > > 
> > > > 
> > > > I confirm the hotfix after enabling VP9 Codec in Vanced settings. Perhaps making it turned on by default in futur release could avoid further issues?
> > > 
> > > 
> > > the right fix buffer option is `spoof protobuf`.
> > 
> > 
> > Weird, I still had the buffer lock with Protobuf but it unlocked when enabling VP9 Codec. Perhaps videos uploaded with VP9 are still locked?
> 
> i don't know but most ppl are able to fix buffer issue with protobuf spoof option

I will do further testings later tonight to give you accurate POC of what I'm supposing here

**Comment by cuynu** [comment] 2023-04-14 17:56
> I will do further testings later tonight to give you accurate POC of what I'm supposing here

okay, but anyway `enable VP9 codec` options are not related anything to buffer issue.

**Comment by S0GDevs** [comment] 2023-04-14 20:37
> > I will do further testings later tonight to give you accurate POC of what I'm supposing here
> 
> okay, but anyway `enable VP9 codec` options are not related anything to buffer issue.

So, you're right. Just enabling Protobuf works.
Guess we can consider this closed

**Comment by doumeki** [comment] 2023-05-13 15:25
I try to use 18.02.33 and disable QUIC seems ok. but 18.01.38 I didn't find the option. and again, problem reproduced although I use the fix option in .38 apk.

**Comment by cuynu** [comment] 2023-05-13 15:34
> I try to use 18.02.33 and disable QUIC seems ok. but 18.01.38 I didn't find the option. and again, problem reproduced although I use the fix option in .38 apk.

your account get buffering playback by google on modified client, you must use 18.02.33 to spoof app signature to original youtube app

**Comment by aryanh0911** [comment] 2023-05-22 08:11
> I also have this issue. I noticed that on my phone running Revanced Extended I don't have this problem with the same microg version and the same google account.
> 
> Yes, I have a couple of beautiful samsung oled tablets running android 6. I tried your version (thanks btw) and it works except for this 1min thing.
> 
> Is there any way of making a 17.34.36 Revanced Extended?

Using Revanced Extended solved it for me as well.

**Comment by TrainedPro** [comment] 2023-05-22 08:18
> > I also have this issue. I noticed that on my phone running Revanced Extended I don't have this problem with the same microg version and the same google account.
> > 
> > Yes, I have a couple of beautiful samsung oled tablets running android 6. I tried your version (thanks btw) and it works except for this 1min thing.
> > 
> > Is there any way of making a 17.34.36 Revanced Extended?
> 
> Using Revanced Extended solved it for me as well.

**SOLUTION:** Please follow this [reddit guide](https://www.reddit.com/r/revancedapp/comments/12ua83s/solution_to_playback_issues_on_android_671/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) that i made. It seems to work everyone i tried it for.

Let me know if it doesn't work

**Comment by TheDaDao** [comment] 2023-06-17 14:46
> > > I also have this issue. I noticed that on my phone running Revanced Extended I don't have this problem with the same microg version and the same google account.
> > > Yes, I have a couple of beautiful samsung oled tablets running android 6. I tried your version (thanks btw) and it works except for this 1min thing.
> > > Is there any way of making a 17.34.36 Revanced Extended?
> > 
> > 
> > Using Revanced Extended solved it for me as well.
> 
> **SOLUTION:** Please follow this [reddit guide](https://www.reddit.com/r/revancedapp/comments/12ua83s/solution_to_playback_issues_on_android_671/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) that i made. It seems to work everyone i tried it for.
> 
> Let me know if it doesn't work

It looks like the reddit g6ide is inaccessible as the subreddit it's on has gone private. I was guessing this was for the API protests and waited but as it still isn't back I suppose it is either going for the indefinite protest or was down for other reasons.

Could you provide the guide here or on another site?

**Comment by cuynu** [comment] 2023-06-17 15:56
> > > > I also have this issue. I noticed that on my phone running Revanced Extended I don't have this problem with the same microg version and the same google account.
> > > > Yes, I have a couple of beautiful samsung oled tablets running android 6. I tried your version (thanks btw) and it works except for this 1min thing.
> > > > Is there any way of making a 17.34.36 Revanced Extended?
> > > 
> > > 
> > > Using Revanced Extended solved it for me as well.
> > 
> > 
> > **SOLUTION:** Please follow this [reddit guide](https://www.reddit.com/r/revancedapp/comments/12ua83s/solution_to_playback_issues_on_android_671/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) that i made. It seems to work everyone i tried it for.
> > Let me know if it doesn't work
> 
> It looks like the reddit guide is inaccessible as the subreddit it's on has gone private.
> 
> I was guessing this was for the API protests and waited but as it still isn't back I suppose they are either going for the indefinite protest or the subreddit was privated for other reasons.
> 
> Could you provide the guide here or on another site?

that guide just is revanced build instructions

**Comment by Vadimhtml** [comment] 2023-06-18 07:11
> Could you provide the guide here or on another site?

I do not have access to Reddit, but there is a solution to the problem. You need to download the extended version of Youtube ReVanced and complete the settings.

Settings -> ReVanced Extended -> Miscellaneous -> Spoof app version (ON) + Spoof app version target (16.8.35)

**Comment by DanielX99** [comment] 2023-06-19 02:44
> > ¿Podría proporcionar la guía aquí o en otro sitio?
> 
> No tengo acceso a Reddit, pero hay una solución al problema. Debe descargar la versión extendida de Youtube ReVanced y completar la configuración.
> 
> Configuración -> ReVanced Extended -> Varios -> Versión de la aplicación falsa (ON) + Destino de la versión de la aplicación falsa (16.8.35)

friend, do you have the "apk" of the version you mention or other solution?

**Comment by TrainedPro** [comment] 2023-06-19 14:27
> It looks like the reddit guide is inaccessible as the subreddit it's on has gone private.
> 
> I was guessing this was for the API protests and waited but as it still isn't back I suppose they are either going for the indefinite protest or the subreddit was privated for other reasons.
> 
> Could you provide the guide here or on another site?

### This is copy pasted from Reddit. It is not just a build guide. I have 3 main solutions for the problem:

I would like to start this short post by thanking the developers  [**kitadai31**](https://github.com/kitadai31) and [**inotia00**](https://github.com/inotia00) for their contributions.

&#x200B;

The link to the original GitHub repository's Wiki is [this!](https://github.com/kitadai31/revanced-patches-android6-7/wiki/How-to-build) You can build it here yourself but unfortunately this **did not** work for me as the build always failed. Even when i built it on my newer device and transferred the APK, it did not work.

&#x200B;

* The solution that i am posting, which worked for me is on [this link.](https://forum.xda-developers.com/t/app-8-0-guides-revanced-revanced-extended.4523967/#:~:text=Download%20Official%20ReVanced%20%26%20ReVanced%20Extended) I am not allowed to post direct executables here so this is the best i can do. Go to the bottom of that post **(Nov 27, 2022)** and there is your solution labelled **"(Android 6.0-7.1) ReVanced Extended (17-04-2023)"**. You just need to install Revanced Extended now and it should work!

&#x200B;

* If this solution does not work, i recommend building it on your PC (if building it on your phone did not work for you), the guide to which is [here.](https://github.com/kitadai31/revanced-patches-android6-7/wiki/How-to-build#:~:text=com/decipher3114/Revancify-,Method%204.%20Using%20ReVanced%20Builder,-ReVanced%20Builder%20is)

&#x200B;

* And the final solution i have that is guaranteed to work on even older devices is using FireFox on your mobile device with uBlock. I used this, and it was pretty good but did not have SponsorBlock and a lot of other features.

&#x200B;

Hope this helps, as Vanced going down for me did effect my entertainment quite a bit.

&#x200B;

**Disclaimer:** It will always be better to build your own version of the app as you will know what is in it. Installing APKs that are pre-built should never be done unless from a highly reputable source. I have no affiliation with any of these developers, I am just posting a guide.

**Comment by cuynu** [comment] 2023-06-19 14:35
Don't know why its doesn't work for some ppl but i just tested on ten devices with 17.39.35 and Android 7 with logged in different Google account each devices but all of these devices are still works fine with no playback

**Closed** 2023-06-19 14:35 UTC
Labels: bug

**Comment by DanielX99** [comment] 2023-06-25 23:50
Una pregunta todavia no hay solucion?

**Comment by LCPallares** [comment] 2023-07-26 22:14
> Una pregunta todavia no hay solucion?
> 

Estoy en lo mismo, acabo de probar, Revanced extended>Otros>desactivar protocolo quic.
Justo el video que se pauso se reprodujo todo, voy a ver si funcionó

**Comment by sophin123** [comment] 2023-07-28 11:47
For me I had to switch channel to make it work. Seems like account issues to me.

**Comment by my-alok** [comment] 2023-07-31 05:12
I just started having this issue and none of the solutions above seems to work. Please help

**Comment by piixelboii** [comment] 2023-08-05 14:33
Turn off external player in the Vanced Settings Or Revanced Extended Settings.  (It is under miscellaneous section)
It worked for me like a charm.

**Comment by futiele** [comment] 2023-08-08 04:58
it's strange. adguard player works. can't vanced youtube do like that？

**Comment by Rohank42** [comment] 2023-08-08 05:21
> Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account

Is there any solution other than changing account used?

**Comment by gambap** [comment] 2023-08-08 07:46
setting -> vanced -> video -> disable protobuf spoof 
 TY Vanced v18.02.33 worked for me

**Comment by gptshubham595** [comment] 2023-08-08 08:27
Unable to find vanced in settings?
![Screenshot_2023-08-08-13-57-09-47](https://github.com/cuynu/ytvancedx/assets/24877361/b821d78b-f935-4638-bb47-63c50713ea7a)

**Comment by gptshubham595** [comment] 2023-08-08 09:08
Not working

**Comment by futiele** [comment] 2023-08-08 09:12
> 

share video to adguard player

**Comment by SlavAnd** [comment] 2023-08-08 09:57
The problem's the profile/account, not the settings.

**Comment by gptshubham595** [comment] 2023-08-08 10:03
I tried uninstalling microg and reinstall, without login and incognito I tested, but still I am facing the same issue stopping after 1min

**Comment by bandabromuro** [comment] 2023-08-08 19:42
sure 100% working aswell VANCED EXTEND ciao

**Comment by TapeeTomat** [comment] 2023-08-09 02:01
remove google account on vanced, log out log in google account on your phone.

**Comment by AndreiAdii** [comment] 2023-08-09 17:44
> setting -> vanced -> video -> disable protobuf spoof TY Vanced v18.02.33 worked for me

this worked for me. Vanced v18.02.33 dark

**Comment by gptshubham595** [comment] 2023-08-10 05:19
Logged out and login with another account worked for me

**Comment by MaddoxxIV** [comment] 2023-08-11 00:44
> setting -> vanced -> video -> disable protobuf spoof TY Vanced v18.02.33 worked for me

This worked!

**Comment by donjonne** [comment] 2023-08-11 03:48
> > setting -> vanced -> video -> disable protobuf spoof TY Vanced v18.02.33 worked for me

still working?

**Comment by dondeepak** [comment] 2023-08-11 04:44
No it's not working video still stops playing after sometimes

**Comment by BLEGBORN** [comment] 2023-08-11 06:44
Same for me the protobuf method dose not worked

**Comment by dvinnci** [comment] 2023-08-11 16:37
the meth

> 

nope its not work

**Comment by dvinnci** [comment] 2023-08-11 16:37
> > > setting -> vanced -> video -> disable protobuf spoof TY Vanced v18.02.33 worked for me
> 
> still working?

nope

**Comment by SlavAnd** [comment] 2023-08-12 00:08
Only 2 things that I've tested have worked so far:
1. ReVanced
2. Vanced 17.33.42 Black

**Comment by BLEGBORN** [comment] 2023-08-12 01:07
Revanced works for me but for a 1 to 2 min and then it auto turn spoof option on  and it stops working, I need to test your way 17.33.42 but before that the only thing worked so far was using 2nd account, it is working fine with it so I guessing it is Google side restriction that brokes accounts that under some redflags.

**Comment by MaddoxxIV** [comment] 2023-08-12 22:18
nope

**Comment by Rohank42** [comment] 2023-08-13 02:49
> Revanced works for me but for a 1 to 2 min and then it auto turn spoof option on and it stops working, I need to test your way 17.33.42 but before that the only thing worked so far was using 2nd account, it is working fine with it so I guessing it is Google side restriction that brokes accounts that under some redflags. Upd: yeah 17.33.42 did nothing for me. Upd2: I just tried ReVanced extended 18.30.37 dark and it works fine with the main account, try this and say if did works for you.

Hello, well believe it or not but your method worked, it looks like using revanced extended resetted the account settings whatever Google had put, after using revanced extended i can play videos from my main account normally on both original YouTube and revanced, but yeah i have deleted the 3rd party ones and now using original YouTube app but thanks for your help!!

**Comment by BLEGBORN** [comment] 2023-08-13 03:00
> > Revanced works for me but for a 1 to 2 min and then it auto turn spoof option on and it stops working, I need to test your way 17.33.42 but before that the only thing worked so far was using 2nd account, it is working fine with it so I guessing it is Google side restriction that brokes accounts that under some redflags. Upd: yeah 17.33.42 did nothing for me. Upd2: I just tried ReVanced extended 18.30.37 dark and it works fine with the main account, try this and say if did works for you.
> 
> Hello, well believe it or not but your method worked, it looks like using revanced extended resetted the account settings whatever Google had put, after using revanced extended i can play videos from my main account normally on both original YouTube and revanced, but yeah i have deleted the 3rd party ones and now using original YouTube app but thanks for your help!!

Wow,  that nice glad it helped. I just checked I'm not such lucky for vanced(old) and revanced are still broken so I using for now extended. But yeah have a good day!

**Comment by itobey** [comment] 2023-08-13 13:51
Switching to Revanced worked for me: https://www.reddit.com/r/revancedapp/comments/11b6zy4/how_to_use_revanced_cli_for_nonroot_users_step_by/

**Comment by donjonne** [comment] 2023-08-13 17:23
hei guys i posted a better description of my fix on the other bug page
but in short:
delete vanced
switch accounts in youtube app(normal)
force stop and disable normal youtube app
reinstall vanced( i used black hot fix universal 18.0.33)
enable spoofing on settings inside vanced
i did this on 3 phones and it worked

**Comment by Straces** [comment] 2023-08-14 06:06
There are 2 ways, one is Youtube ReVanced and second is on youtube Vanced: delete cache, delete data, uninstall and install back Youtube Vanced 18.02.33, this worked for me on two devices :-)

**Comment by abhiP2296** [comment] 2023-08-14 14:41
> There are 2 ways, [contains r*****d] on youtube Vanced: delete cache, delete data, uninstall and install back Youtube Vanced 18.02.33, this worked for me on two devices :-)

Does not work.

**Comment by donjonne** [comment] 2023-08-14 23:30
> > There are 2 ways, [contains r*****d] on youtube Vanced: delete cache, delete data, uninstall and install back Youtube Vanced 18.02.33, this worked for me on two devices :-)
> 
> Does not work.

Did you try my method?

**Comment by cuynu** [comment] 2023-08-15 00:50
> > setting -> vanced -> video -> disable protobuf spoof
> > TY Vanced v18.02.33 worked for me
> 
> This worked for v18.31.37

Vanced v18.31.37? or that suck R*****d?

**Comment by benji62f** [comment] 2023-08-15 00:53
Had the same problem, what I did to fix it:
- Update YT ReVanced Extended to last version (18.30.37);
- Update MicroG to last version;
- In YT Revanced Extended : Settings > ReVanced Extended > Miscellaneous > Turn on "Falsify player settings" in the bottom of the screen.
Now it's working well.

**Comment by benji62f** [comment] 2023-08-15 01:05
Had the same problem with YT ReVanced Extended, what I did to fix it:

- Update YT ReVanced Extended to last version (18.30.37);
- Update MicroG to last version;
- In YT Revanced Extended : Settings > ReVanced Extended > Miscellaneous > Turn on "Falsify player settings" in the bottom of the screen.

Now it's working well.

**NB:** My interface is in French. I translated the setting names for you, they may be slightly different.

**Comment by Speed60580** [comment] 2023-08-15 18:19
Same for me, it was working perfectly before today. :'(

**Comment by SillentStriker** [comment] 2023-08-15 19:56
> setting -> vanced -> video -> disable protobuf spoof TY Vanced v18.02.33 worked for me

This worked for me as well!

**Comment by gamesguru** [comment] 2023-08-17 16:11
None of these solutions are working for me. I started having issues, seems like it's off and on for a few months now.

I'm wondering what the potential cause is and any possible ways to address that.

**Comment by Rohank42** [comment] 2023-08-17 20:17
Hmm,i had the same issue,my issue got solved after i installed revanced
extended,then signed in with the acc i was having issue with and just
played a video,i was using revanced when i got soft banned from Google,but
revanced extended fixed it for me idk why.

**Comment by donjonne** [comment] 2023-08-17 22:23
@Speed60580
@gamesguru
@Rohank42
 

quick test and the latest release edited fix works
https://github.com/cuynu/archive/releases/tag/18.21.34

the 129 mb file
18.21.34 black universal

**Comment by arickec** [comment] 2023-08-17 22:36
Hi, Did it work for you?

**Comment by cuynu** [comment] 2023-08-17 22:37
> Hi, Did it work for you?

works

**Comment by arickec** [comment] 2023-08-17 22:49
> > Hi, Did it work for you?
> 
> works

Do I need a specific version of vanced microG?  I have 0.2.27.231413 installed.  Thank you

**Comment by donjonne** [comment] 2023-08-18 02:45
@arickec 

Nope, i havent updated my microg and it werks

**Comment by gamesguru** [comment] 2023-08-18 04:08
Yes, [18.21.34](https://github.com/cuynu/archive/releases/tag/18.21.34) is getting passed the usual sticking point!

**Comment by Rohank42** [comment] 2023-08-18 05:06
My YouTube is working fine but thanks i will look into the updated app
asap👍

**Comment by Speed60580** [comment] 2023-08-18 09:48
@donjonne Thank you very much donjonne!
The 18.02.33 doesn't work but yours works perfectly !!.... For the moment ^^'

**Comment by frasu** [comment] 2023-08-18 21:55
> @Speed60580 @gamesguru @Rohank42
> 
> quick test and the latest release edited fix works https://github.com/cuynu/archive/releases/tag/18.21.34
> 
> the 129 mb file 18.21.34 black universal

Just after the installation this version was working fine with ads on main page but no 50 sec glitch.

After one day the problem returns :(

How to fix it on 18.21.34? There is no protobuf option in the settings.

**Comment by arickec** [comment] 2023-08-18 23:18
At the moment version 18.21.34 allows me to continue playing after 1 min of video(1 day of use) .  I don't know if it's a bug or if I had to activate some configuration, but when I advance or delay the video, it doesn't show me the preview image.  Any solution?  Thank you

**Comment by frasu** [comment] 2023-08-19 10:37
> How to fix it on 18.21.34? There is no protobuf option in the settings.
Ok, I found "cheat parameters" option in the settings and it works. 
But I have ads on main page still.

**Comment by gptshubham595** [comment] 2023-08-19 18:29
> @Speed60580 @gamesguru @Rohank42
> 
> quick test and the latest release edited fix works https://github.com/cuynu/archive/releases/tag/18.21.34
> 
> the 129 mb file 18.21.34 black universal

Thanks a ton 🙏

**Comment by KingAnge978** [comment] 2023-08-21 16:21
> Google is testing block video playback on 3rd-party/modified client in some accounts. That mean if you having buffer issue (video not loading) in your current Google account, you have to change other Google account

Either google is blocking me personally or this solution isn't working for me

**Comment by abhiP2296** [comment] 2023-08-24 10:27
> @Speed60580 @gamesguru @Rohank42
> 
> quick test and the latest release edited fix works https://github.com/cuynu/archive/releases/tag/18.21.34
> 
> the 129 mb file 18.21.34 black universal

Working

**Comment by SlavAnd** [comment] 2023-09-11 10:01
Would be nice if we could get it working on Android 6 too.
